### ISSUE TITLE
missing requirements.txt

### ISSUE THREAD

**Issue by kszarek** [joxeankoret/multiav#1]
Can you please provide `requirements.txt` and which python version should I use?

**Comment by joxeankoret** [comment]
OK, I will do soon.

**Comment by llazzaro** [comment]
Hi,
On https://github.com/joxeankoret/multiav/blob/master/setup.py#L17 you have the requirements.
doing a python setup.py install, python setup.py develop or pip install git+https://github.com/joxeankoret/multiav.git should install all project deps.
If any project dep is missing please let me know.
I'm writting a tutorial on how to setup a vm for using this project with nginx+uwsgi.
