### ISSUE TITLE
multiav.py not found

### ISSUE THREAD

**Issue by mrloverman5** [joxeankoret/multiav#13]
Thankyou for writing an amazing tool, however I am unable to get it to work on kali 64bit, I keep getting and error multiav.py no such file or directory, I have tried reinstalling a few times now, is it possible you could briefly go over the installation, as the error makes me think I have made a mistake during installation. I have tried everything according to your book. 
Thankyou

**Comment by joxeankoret** [comment]
You must be more specific. How are you using it? Can you paste how you try to run the command?

**Comment by mrloverman5** [comment]
Hi thanks for your reply, I have been trying python multiav.py /root/malware/eicar.com.txt in kali and get 
python: can't open file 'multiav.py': [Errno 2] No such file or directory as a response, in Ubuntu I have been trying exactly as it is written in your book.

**Comment by joxeankoret** [comment]
The script multiav.py is not in your path. Sorry, looking to your comments, I doubt I can really help you at all.

**Comment by mrloverman5** [comment]
Hi maybe I'm misunderstanding but there isnt a maltiav.py script in the source code either?

**Comment by joxeankoret** [comment]
We changed it some time ago. Now, the example script to use the API is this one: https://github.com/joxeankoret/multiav/blob/master/multiav/scripts/multiav-scan.py

**Comment by mishamehra** [comment]
while running the following command in ubuntu
 python3 multiav/scripts/multiav-scan.py /home/misha-151/Desktop/Income\ Tax\ Challan.scr 
i am getting the following error
  File "multiav/scripts/multiav-scan.py", line 17
    print "Usage:", sys.argv[0], "<path>"

pls help!!

**Comment by joxeankoret** [comment]
First of all: please, open another thread to discuss different issues. Second of: please give more details about the error, otherwise, it's impossible to fix what I can't understand.
