### ISSUE TITLE
core.py line# 108 not being execute and causing error->  local variable 'cmd' referenced before assignment*

### ISSUE THREAD

**Issue by palindro** [joxeankoret/multiav#16]
Line# 108 not being execute ->  cmd = self.build_cmd(path)
And therefore Error coming while executing Line# 113 -> output = check_output(cmd)
                                    UnboundLocalError: local variable 'cmd' referenced before assignment**

The complete error is shown below:
# multiav-scan.py  eicer.com

Traceback (most recent call last):
  File "/bin/multiav-scan.py", line 25, in <module>
    main(sys.argv[1])
  File "/bin/multiav-scan.py", line 11, in main
    ret = multi_av.scan(path, AV_SPEED_ALL)
  File "/usr/lib/python2.7/site-packages/multiav/core.py", line 593, in scan
    return self.single_scan(path, max_speed)
  File "/usr/lib/python2.7/site-packages/multiav/core.py", line 598, in single_scan
    results = self.scan_one(av_engine, path, results, max_speed)
  File "/usr/lib/python2.7/site-packages/multiav/core.py", line 607, in scan_one
    av.scan(path)
  File "/usr/lib/python2.7/site-packages/multiav/core.py", line 118, in scan
    **output = check_output(cmd)
UnboundLocalError: local variable 'cmd' referenced before assignment**

**Comment by joxeankoret** [comment]
Read the next line please: https://github.com/joxeankoret/multiav/blob/master/multiav/core.py#L109

```
    except: # There is no entry in the *.cfg file for this AV engine?
```

**Comment by palindro** [comment]
Thanks for reply.

Q1:  **Pls clear, line# 109 is for which all *.cfg file.** 
                             except: # There is no entry in the *.cfg file for this AV engine?

**My multiav-master folder has only 1 cfg file that is -> /root/multiav-master/multiav/config.cfg**
**Whereas, the install dir /usr/lib/python2.7/site-packages/multiav/**  does not have any cfg file.

I have no other *.cfg file found in my PC. 

The config file in my setup: /root/multiav-master/multiav/config.cfg, I have enabled only two (2)  scanners, namely  comdo and clamscan.  All others scanners are set as DISABLED=1. The entries are as follows:

[F-Prot]
    PATH= /usr/local/bin/f-prot/fpscan
   ARGUMENTS= -r -v 0
   DISABLED =1
 
[Comodo]
 PATH=/opt/COMODO/cmdscan
ARGUMENTS=-s $FILE -v 

[ClamScan]
PATH=/bin/clamscan
#ARGUMENTS= -v

[ESET]
PATH=.....
ARGUMENTS=....
DISABLED =1

[Avira]
PATH=.....
ARGUMENTS=....
DISABLED =1

------------------------------------------
Q2:  I am executing it as 
  # multiav-scan.py  input-test-file

  As per line # 108, cmd = self.build_cmd(path) 
It fails, & then executes line# 109 except... & line#110 -> pass
Upto this, It is OK

Bur then, while executing Line# 113 -> output = check_output(cmd)
How it will get the value of cmd? And the throwing the Error:

UnboundLocalError: local variable 'cmd' referenced before assignment**

Further, I have not the where  **self.build_cmd(path)** is defined. though in core.py script, it is called in many places. 

-------------------------------------------------
Q3: Infact I modified the declaration of self.engines from 
self.engines = [CFProtScanner,  CComodoScanner,      CEsetScanner,
                    CAviraScanner,  CBitDefenderScanner, CSophosScanner,
                    CAvastScanner,  CAvgScanner,         CDrWebScanner,
                    CMcAfeeScanner, CIkarusScanner,      CFSecureScanner,
                    CKasperskyScanner, CZavScanner,      CEScanScanner,
                    CCyrenScanner,  CQuickHealScanner]

to 

self.engines = [CComodoScanner,      CClamScanScanner]

Even then, the error is same: while executing line#113
UnboundLocalError: local variable 'cmd' referenced before assignment**

**Comment by palindro** [comment]
What is the value set to **cmd** if scanner are installed or everything is OK.

  cmd = self.build_cmd(path)

Because in debugging, i found **path** is  arg[1] or given-input-test-file

**Comment by palindro** [comment]
Got it. It worked.

**Comment by palindro** [comment]
Got it. It worked.

**Comment by joxeankoret** [comment]
No worries, it's usual to have problems setting it up. I will try to add something to, at the very least, say where is it failing.
