### ISSUE TITLE
help to install joxeankoret

### ISSUE THREAD

**Issue by blackhands** [joxeankoret/multiav#17]
hi joxeankoret

plz help me to install multiav
.i am problem to run multiav install to ubento  .

You're not prepared to install video tutorial?

thanks joxeankoret

**Comment by againer** [comment]
What problems are you running into @blackhands ?

**Comment by mishamehra** [comment]
there are some basic things u need to configure properly to run this multiav scanner
1. python installed (its by default in ubuntu)
2. All avs installed (as mentioned in config.cfg file) disable those which are not
3. Change path of config file in core.py 

i did these things and got this code running on my machine!!

**Comment by againer** [comment]
@mishamehra: where are you putting your config?

Having to change core.py to point to the correct config path seems wrong...

@joxeankoret can you provide clear instructions on how to get this running correctly when using pip? Thanks.

Also, instructions on how to run the web api and the client would be helpful.

```
Traceback (most recent call last):
  File "../../envs/tastic/lib/python2.7/site-packages/multiav/webapi.py", line 27, in <module>
    raise Exception('runserver.py must be run in the directory {0}'.format(ROOT_PATH))
Exception: runserver.py must be run in the directory ../../envs/tastic/lib/python2.7/site-packages/multiav
```

**Comment by joxeankoret** [comment]
Well... First of all: remember this from the readme file:

```
it's not designed to be executed as an independent tool but rather to be used as an API for other tools
```

Second, I have no idea how it works with PIP as I don't use PIP.

In any case, I will write documentation and a tutorial because every once in a while I receive some similar question.

**Comment by mishamehra** [comment]
you have to mention the exact path name of the file (config.cgf) in core.py file under 
class CMultiAV:
  def **init**(self, cfg = "pathname/config.cfg"):

**Comment by blackhands** [comment]
```
Traceback (most recent call last):
  File "multiav-scan.py", line 23, in <module>
    main(sys.argv[1])
  File "multiav-scan.py", line 9, in main
    ret = multi_av.scan(path, AV_SPEED_ALL)
  File "/usr/local/lib/python2.7/dist-packages/multiav-0.1.0-py2.7.egg/multiav/core.py", line 587, in scan
    return self.single_scan(path, max_speed)
  File "/usr/local/lib/python2.7/dist-packages/multiav-0.1.0-py2.7.egg/multiav/core.py", line 592, in single_scan
    results = self.scan_one(av_engine, path, results, max_speed)
  File "/usr/local/lib/python2.7/dist-packages/multiav-0.1.0-py2.7.egg/multiav/core.py", line 601, in scan_one
    av.scan(path)
  File "/usr/local/lib/python2.7/dist-packages/multiav-0.1.0-py2.7.egg/multiav/core.py", line 113, in scan
    output = check_output(cmd)
UnboundLocalError: local variable 'cmd' referenced before assignment
admin@ubuntu:~/multiav/multiav/scripts$ 

```

I need a setup tutorial I and my acquaintance to Python is very low.

For this project requires a simple training is very good

 thanks
