### ISSUE TITLE
Problems using package

### ISSUE THREAD

**Issue by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [joxeankoret/multiav#18]
Honestly can't get this to work in any form. 

Steps so far

> python setup.py install
> configured cfg and made sure AV clients were install
> Launch python interpreter and import multiav (succeeded)

Then when trying to do anything I'm basically getting Module object has no attribute

```
>>> multi_av = multiav.CMultiAV()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'CMultiAV'
```

I confirmed the packages were install against Pypi:
**PIP:**

pip install multiav
Requirement already satisfied (use --upgrade to upgrade): multiav in ./lib/python2.7/site-packages/multiav-0.1.0-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): web.py in ./lib/python2.7/site-packages/web.py-0.40.dev0-py2.7.egg (from multiav)
Requirement already satisfied (use --upgrade to upgrade): pyClamd in ./lib/python2.7/site-packages/pyClamd-0.3.17-py2.7.egg (from multiav)

**EASY_Install**

Searching for multiav
Best match: multiav 0.1.0
Processing multiav-0.1.0-py2.7.egg
multiav 0.1.0 is already the active version in easy-install.pth
Installing multiav-client.py script to /home/*****_/Desktop/multiav-master/pyav/bin
Installing runserver.py script to /home/**_**_/Desktop/multiav-master/pyav/bin
Installing multiav-scan.py script to /home/**_***/Desktop/multiav-master/pyav/bin

Using /home/******/Desktop/multiav-master/pyav/lib/python2.7/site-packages/multiav-0.1.0-py2.7.egg
Processing dependencies for multiav
Finished processing dependencies for multiav

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
I'm an idiot.

**https://github.com/joxeankoret/multiav/issues/11**

Maybe update the docs?

**Comment by joxeankoret** [comment]
Yes, I agree, I have to update the docs because they are very outdated.
