### ISSUE TITLE
Instalation Guild

### ISSUE THREAD

**Issue by ArshamCoder** [joxeankoret/multiav#28]
Hello Sir
i`m newbie in Linux OS an py language
but i need to install your amazing Multi-AV 
would you please help me how can I install it ? or how can i scan my file with all 18 antivirus 
please help me is you can 
thanks in advance

**Comment by joxeankoret** [comment]
It looks like homework, and I'm not going to do it for you. However, I will help you giving out the steps so you can (if you want) do it yourself:

1. Get a copy of the GIT repo and install it (tip: setup.py).
2. Install the AV or AVs that you want that are supported (https://github.com/joxeankoret/multiav/blob/master/multiav/config.cfg).
3. Edit your config.cfg file and enable/disable the engines you want to use.
4. You might need to adjust the paths of the command line tools it calls.
5. Use the basic command line tool multiav.py or, better yet, write your own tool based on this API (as this project, MultiAV, was meant as an easy to use API, not a tool).

**Comment by ArshamCoder** [comment]
hello sir
tnx for reply
actually i did step 1 , 2 , 3  but i stock on step 4
would you please tel me how can i adjust the paths of the command line tools it calls ?
i install F-Prot AV but i don`t know how  adjust the paths of it
would you please show me a picture of it ? i need it so badly
and it shows me " path not found error "
thanks in advance

**Comment by joxeankoret** [comment]
IIRC, the command line scanner is called "fpscan". In a terminal, execute:

```$ which fpscan```

It will output something like "/opt/f-prot/fpscan". Take this path and replace in config.cfg (https://github.com/joxeankoret/multiav/blob/master/multiav/config.cfg#L6) the PATH line and set DISABLED=0.

Do the same for every single AV you want to support.
