### ISSUE TITLE
Installer?

### ISSUE THREAD

**Issue by Feathur** [joxeankoret/multiav#3]
Do you by chance have an installer of some kind to put some/all of these on <insert os here> automatically?

(preferably CentOS, Ubuntu or Debian, but I'm not too picky)

**Comment by llazzaro** [comment]
I can do a pull request to create the whole project as a python module. it can be published on pypi or from git with those changes

**Comment by joxeankoret** [comment]
It would be very appreciated!

**Comment by Feathur** [comment]
I was specifically thinking of an installer for both your code and the modules it requires for scanning.

**Comment by llazzaro** [comment]
I had done some something in my fork https://github.com/llazzaro/multiav
I will test it again later.
It will install tree commands multiav-client.py, multiav-scan.py and webapi.py

I recommend to use virutalenv and install my fork with pip
pip install git+https://github.com/llazzaro/multiav

I will do a pull request later.
This will not install any av, but it will install all dependencies (I also added a requirements_dev.txt)

**Comment by joxeankoret** [comment]
Hi @llazzaro , could you send me one (or various) Pull Requests to integrate you changes you made into your fork? I really liked some of the changes.

**Comment by llazzaro** [comment]
thanks! I will do it. I need to fix a bug with the static files when runserver is executed outside project.
I hope to do the pull request this weekend, with the bug fix.

After doing that pull request I will work on an ansible script for installing AVs.

**Comment by llazzaro** [comment]
I think we can close this. what do you think @joxeankoret ?

**Comment by joxeankoret** [comment]
I think so
